use_frameworks!

platform :ios, '10.0'

target 'SecureStoragesLib_Example' do
  pod 'SecureStoragesLib', :path => '../'

  target 'SecureStoragesLib_Tests' do
    inherit! :search_paths

    
  end
end
